"""Excel worksheet → staging_excel loader (shared by validate and import pipelines)."""
from __future__ import annotations

import sqlite3
from typing import TYPE_CHECKING

from doors_excel.core.transformation.hashing import hash_markdown
from doors_excel.infrastructure.database.repositories import StagingExcelRepository

if TYPE_CHECKING:
    from openpyxl.worksheet.worksheet import Worksheet

    from doors_excel.core.validation.models import ModuleConfig


def load_excel_to_staging(
    ws: "Worksheet",
    conn: sqlite3.Connection,
    session_id: str,
    module_config: "ModuleConfig",
    *,
    trim_whitespace: bool = True,
) -> None:
    """Read all rows from *ws* and insert into ``staging_excel``."""
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return

    headers = [str(cell) if cell is not None else "" for cell in rows[0]]
    oid_col = module_config.object_id_column

    text_cols = {
        m.column
        for m in module_config.column_mappings
        if m.attribute_type == "Text"
    }

    from doors_excel.core.transformation.smart_split import join_split_columns

    # Detect overflow columns generated by _expand_long_values on export.
    # Any header of the form "<mapped_col>_<digits>" where <mapped_col> is
    # also present in headers is treated as an overflow continuation column.
    mapped_cols = {m.column for m in module_config.column_mappings}
    overflow_bases: dict[str, list[str]] = {}
    for h in headers:
        if h in mapped_cols:
            continue  # real column, never an overflow
        for base in mapped_cols:
            if base in headers and h.startswith(f"{base}_") and h[len(base) + 1:].isdigit():
                overflow_bases.setdefault(base, []).append(h)

    overflow_col_names: set[str] = {
        oc for overflows in overflow_bases.values() for oc in overflows
    }

    staging: list[dict] = []
    for row_idx, row in enumerate(rows[1:], start=2):
        object_id: int | None = None
        if oid_col in headers:
            raw_oid = row[headers.index(oid_col)] if headers.index(oid_col) < len(row) else None
            try:
                object_id = int(raw_oid) if raw_oid is not None and str(raw_oid).strip() else None
            except (ValueError, TypeError):
                object_id = None

        for col_idx, header in enumerate(headers):
            if not header:
                continue
            if header in overflow_col_names:
                continue  # handled as part of base column join

            value = row[col_idx] if col_idx < len(row) else None

            # Join overflow columns if this base column has overflow continuations.
            # Only join when at least one overflow cell is non-None, to avoid
            # changing None → "" for rows that were never split.
            if header in overflow_bases:
                overflow_vals = {
                    oc: row[headers.index(oc)] if headers.index(oc) < len(row) else None
                    for oc in overflow_bases[header]
                }
                if value is not None or any(v is not None for v in overflow_vals.values()):
                    base_val = str(value) if value is not None else ""
                    row_dict: dict[str, str | None] = {header: base_val}
                    for oc, oc_val in overflow_vals.items():
                        row_dict[oc] = str(oc_val) if oc_val is not None else ""
                    value = join_split_columns(header, row_dict)

            # Trim whitespace for non-Text, non-None string values
            if value is not None:
                str_value = str(value)
                # Only trim if this is not a Text column (Text columns preserve RTF formatting)
                # and if trim_whitespace is enabled
                if header not in text_cols and trim_whitespace:
                    str_value = str_value.strip()
            else:
                str_value = None

            md_hash = (
                hash_markdown(str_value)
                if header in text_cols and str_value is not None
                else None
            )
            staging.append({
                "session_id": session_id,
                "row_number": row_idx,
                "object_id": object_id,
                "attribute": header,
                "value": str_value,
                "md_hash": md_hash,
            })

    StagingExcelRepository(conn).insert_many(staging)
